### ISSUE TITLE
Lora training ?

### ISSUE THREAD

**Issue by axel578** [dome272/wuerstchen#12]
Is it possible to do lora training on these models ?
It would give a big boost to this project, also finetuning on 24 images doesnt give any result at all, why the training stages have no epoch ?

**Comment by dome272** [comment]
We are working on it!

**Comment by danieltanhx** [comment]
https://github.com/huggingface/diffusers/issues/5043

**Comment by maubreville** [comment]
It's possible to train Würstchen with LoRA, see example [in their repo](https://github.com/huggingface/diffusers/blob/main/examples/wuerstchen/text_to_image/train_text_to_image_lora_prior.py)
