### ISSUE TITLE
Image embeddings

### ISSUE THREAD

**Issue by ahmed-mohamed-sn** [dome272/wuerstchen#15]
Is it possible to use Wuerstchen for img2img generation? Like skipping the prior step and using image embedding directly?

**Comment by dome272** [comment]
Yea you can extract image embeddings with the encoder (the EfficientNet) and decode that. But this will almost give you identical outputs, so img2img is not that easily possible. With v3 this should become a bit better by only using Stage B as they should be more powerful. But you can also just do img2img by encoding images and do img2img at Stage C, same as with Stable Diffusion.
The following is from Würstchen v3, but you can do the same with v2. (v3 is not out yet, still working on it)
![image](https://github.com/dome272/Wuerstchen/assets/61938694/cbd9b291-75c0-4a99-ad31-0f0f5243fba6)

**Comment by ahmed-mohamed-sn** [comment]
Thanks @dome272, I'll try it. I am very impressed with the quality and the optimisation.  Great job and can't wait to try v3.
