### ISSUE TITLE
How To Access Model On Diffusers App? 

### ISSUE THREAD

**Issue by Acephalia** [dome272/wuerstchen#21]
Hello the Readme and Diffusers page on HF both state that the model is available in diffusers format. However when using the AppStore app for HF diffusers I cannot see an option for the model to be downloaded. I tried to search for a diffusers version that I could clone in manually but the only model links I found were .pt files. Would anyone be able to point me in the right direction to grabbing a version of this I can run on the diffusers app on osx? 

Thank you.

**Comment by maubreville** [comment]
Hey there, 

the model is part of the diffusers library, but this does not mean it's also available from the diffusers app. As stated in the app, it currently only supports 5 distinct models from the HF hub. 

Best,

Marc
