### ISSUE TITLE
About proper fine-tuning approach

### ISSUE THREAD

**Issue by NTU-P04922004** [dome272/wuerstchen#22]
First of all, thanks for sharing the wonderful work of the Wuerstchen model.
I would like to know what is the proper way to fine-tune Wuerstchen V2 pretrained weights with a small data set.
Should we fine-tune only stage-C or both stage-C and stage-B?
Any advice?

**Comment by maubreville** [comment]
Hey there,

Stage B should be more or less general purpose, so I'd go for fine-tuning stage C :-)

**Comment by dome272** [comment]
Agree

**Comment by NTU-P04922004** [comment]
@maubreville @dome272 
Got it, thanks.
