### ISSUE TITLE
Query About Integrating ControlNet into Wurstchen

### ISSUE THREAD

**Issue by junhoning** [dome272/wuerstchen#23]
Hello Wurstchen Team,

I am intrigued by Wurstchen's capabilities and wonder if there are any plans to integrate ControlNet into the project. ControlNet's advanced image direction features could greatly enhance Wurstchen’s functionality, particularly in controlled image generation.

Could you share any insights on the potential incorporation of ControlNet, or if such an integration is under consideration?

Thank you for your innovative work.

Best regards,

**Comment by dome272** [comment]
Hey, we are already working on controlnets for v3. Feel free to join the discord, we also have a channel for controlnets there

**Comment by junhoning** [comment]
Hello @dome272 ,
Thanks for the response! I'm excited to hear that integration of ControlNet is already in the works for version 3. I'm really looking forward to seeing how these features will be implemented and the impact they will have on controlled image generation.

I will definitely join the Discord and hop into the ControlNet channel for more in-depth discussions.

Have a great day,
