### ISSUE TITLE
Train the model from scatch

### ISSUE THREAD

**Issue by Felix-FN** [dome272/wuerstchen#26]
Hi there,

i have a own Text and Image Dataset and want to train Würstchen with it from scratch, because the Captions are rather unique.
I want to use it as a Txt2Img model only.
How do i need to approach this with your code?

Any help is highly appreciated! :)

**Comment by dome272** [comment]
I think you can just follow the training script in train_c.py and use that and replace the dataset with yours. Let me know if you can get it to work

**Comment by Felix-FN** [comment]
Hi thanks for your answer!
Yeah i could need some more help, because I'm fairly new to the whole topic. Doing my Masters Thesis at THI.

- I want to use a dataset which i generated by my own and is therefore local. What kind of format does the Dataset need to be in order to be understood by the model?
- i get an Error when is start the script without any modification. The Error s as follows: torch.distributed.DistStoreError: No such file or directory. It originates in the ddp_setup-Method. What is expected to be this variable: init_method="file:///mnt/nvme/home/dome/src/würstchen/dist_file69" ?

Sidenote: I run the model on a cluster, not on a local machine

Thank you!

**Comment by dome272** [comment]
Hey thats very cool that you are doing it at THI. But for specific questions, it would be best if you would contact your supervisor directly. But just briefly, my code uses webdataset as the format, so just look that up and see how to organize it. Secondly, the path for 2. needs to be set to some of your own path. Sorry about hardcoding it like this.

**Comment by Felix-FN** [comment]
Deepening the topic since you answered me. Thanks for the Tips!
Closing the Issue
