### ISSUE TITLE
Question about diagram in paper

### ISSUE THREAD

**Issue by Lime-Cakes** [dome272/wuerstchen#4]
I noticed a small oddity with one of the diagram explaining the model architecture in the paper. In the following image,  text-conditioned diffusion model (Stage C) is placed under Stage A, while VQGAN (Stage A) is put under Stage C. While the paper is rather clear about diffusion model being Stage C, with inference starting with Stage C, then B->A, the diagram is slightly confusing. 
![image](https://github.com/dome272/Wuerstchen/assets/91322985/7f7da464-af94-42d3-8b7f-550ff2276732)

**Comment by dome272** [comment]
Sorry yea that is an oopsie in thr Figure. The top row indicating the different stages should be in reverse order. VQGAN is Stage A and the text-conditional model is Stage C.

**Comment by Lime-Cakes** [comment]
Thanks for clarifying! Love your work!
